nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://127.0.0.1:8002']
        allow_methods: ['GET', 'POST']
        allow_headers: ['*']
        max_age: 3600
    paths:
        '^/api/': 
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PATCH', 'PUT', 'DELETE']
            
        '^/': null
        

